[env]
platform = espressif32
board = heltec_wifi_lora_32_V2
framework = arduino
monitor_speed = 115200
lib_deps =
    sandeepmistry/LoRa
build_flags =
    -I src/comum

[env:professor]
build_src_filter =
    +<professor/>
    +<comum/>
    -<aluno/>
upload_port = COM5
monitor_port = COM5

[env:aluno]
build_src_filter =
    +<aluno/>
    +<comum/>
    -<professor/>
upload_port = COM9
monitor_port = COM9