[env]
platform = espressif32
board = heltec_wifi_lora_32_V2
framework = arduino
monitor_speed = 115200
lib_deps =
    sandeepmistry/LoRa
    thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library
build_flags =
    -I src/comum

[env:professor]
build_src_filter =
    +<professor/>
    +<comum/>
    -<aluno/>
upload_port = COM5
monitor_port = COM5

[env:aluno1]
build_src_filter =
    +<aluno/>
    +<comum/>
    -<professor/>
upload_port = COM9
monitor_port = COM9
build_flags =
    ${env.build_flags}
    -DID_ALUNO_CONFIG=\"1\"

[env:aluno2]
build_src_filter =
    +<aluno/>
    +<comum/>
    -<professor/>
upload_port = COM12
monitor_port = COM12
build_flags =
    ${env.build_flags}
    -DID_ALUNO_CONFIG=\"2\"